import sys

from translate import Translator
import socket
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QApplication, QMainWindow, QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 674)
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("\n"
                                 "border-radius: 50px;\n"
                                 "background-color: blue;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setStyleSheet("background-color: blue")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(2, -1, -1, -1)
        self.horizontalLayout_5.setSpacing(33)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setStyleSheet("padding-right: 20px;\n"
                                 "background-color: blue;\n"
                                 "color: white\n"
                                 "")
        self.label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("border-radius: 20px;\n"
                                   "color    : black;\n"
                                   "background-color: white\n"
                                   "")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setStyleSheet("background-color: blue\n"
                                   "")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.verticalLayout_4.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(29, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 317, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.from_len = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.from_len.setFont(font)
        self.from_len.setStyleSheet("color: black")
        self.from_len.setObjectName("from_len")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.from_len.addItem("")
        self.horizontalLayout_4.addWidget(self.from_len)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.from_text = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.from_text.setFont(font)
        self.from_text.setStyleSheet("border-left: 1.5px solid blue;\n"
                                     "border-bottom: 1.5px solid blue;\n"
                                     "border-right: none;\n"
                                     "border-top: none")
        self.from_text.setObjectName("from_text")
        self.verticalLayout.addWidget(self.from_text)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(27, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.to_lang = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.to_lang.setFont(font)
        self.to_lang.setStyleSheet("alternate-background-color:rgb(128,128,128, 0);\n"
                                   "color: black;\n"
                                   "background-color: white;\n"
                                   "border-bottom: 1px solid white\n"
                                   "")
        self.to_lang.setObjectName("to_lang")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.to_lang.addItem("")
        self.horizontalLayout_3.addWidget(self.to_lang)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(28, 1, 14, 1)
        self.horizontalLayout_2.setSpacing(154)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_6.setStyleSheet("border: 1.5px solid blue;\n"
                                   "border-radius: 15px")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.reverse = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.reverse.setFont(font)
        self.reverse.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reverse.setStyleSheet("background-color:  blue;\n"
                                   "color: white;\n"
                                   "padding-bottom: 5px;\n"
                                   "border: 1.5px solid blue;\n"
                                   "border-radius: 10px;\n"
                                   "")
        self.reverse.setObjectName("reverse")
        self.horizontalLayout_2.addWidget(self.reverse)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.to_text = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.to_text.setFont(font)
        self.to_text.setStyleSheet("border-left: 1.5px solid blue;\n"
                                   "border-bottom: 1.5px solid blue;\n"
                                   "border-right: none;\n"
                                   "border-top: none")
        self.to_text.setObjectName("to_text")
        self.verticalLayout_2.addWidget(self.to_text)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setContentsMargins(151, -1, 147, -1)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem3)
        self.translate_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translate_btn.sizePolicy().hasHeightForWidth())
        self.translate_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.translate_btn.setFont(font)
        self.translate_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.translate_btn.setStyleSheet("\n"
                                         "border: 1.5px solid blue;\n"
                                         "border-radius: 25px\n"
                                         "")
        self.translate_btn.setObjectName("translate_btn")
        self.horizontalLayout.addWidget(self.translate_btn)
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_btn.sizePolicy().hasHeightForWidth())
        self.clear_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.clear_btn.setFont(font)
        self.clear_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clear_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.clear_btn.setStyleSheet("background-color: blue;\n"
                                     "color: white;\n"
                                     "border-radius: 25px")
        self.clear_btn.setAutoRepeatDelay(300)
        self.clear_btn.setObjectName("clear_btn")
        self.horizontalLayout.addWidget(self.clear_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 32, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Переводчик"))
        self.label.setText(_translate("MainWindow", "Text translate"))
        self.label_4.setText(_translate("MainWindow", "T"))
        self.from_len.setItemText(0, _translate("MainWindow", "русский"))
        self.from_len.setItemText(1, _translate("MainWindow", "английский"))
        self.from_len.setItemText(2, _translate("MainWindow", "Африканский"))
        self.from_len.setItemText(3, _translate("MainWindow", "гаитянский креольский"))
        self.from_len.setItemText(4, _translate("MainWindow", "албанский"))
        self.from_len.setItemText(5, _translate("MainWindow", "амхарский"))
        self.from_len.setItemText(6, _translate("MainWindow", "арабский"))
        self.from_len.setItemText(7, _translate("MainWindow", "армянский"))
        self.from_len.setItemText(8, _translate("MainWindow", "азербайджанский"))
        self.from_len.setItemText(9, _translate("MainWindow", "баскский"))
        self.from_len.setItemText(10, _translate("MainWindow", "белорусский"))
        self.from_len.setItemText(11, _translate("MainWindow", "бенгальский"))
        self.from_len.setItemText(12, _translate("MainWindow", "боснийский"))
        self.from_len.setItemText(13, _translate("MainWindow", "болгарский"))
        self.from_len.setItemText(14, _translate("MainWindow", "каталонский"))
        self.from_len.setItemText(15, _translate("MainWindow", "хауса"))
        self.from_len.setItemText(16, _translate("MainWindow", "кебуано"))
        self.from_len.setItemText(17, _translate("MainWindow", "чичева"))
        self.from_len.setItemText(18, _translate("MainWindow", "китайский (упрощенный)"))
        self.from_len.setItemText(19, _translate("MainWindow", "китайский (традиционный)"))
        self.from_len.setItemText(20, _translate("MainWindow", "корсиканский"))
        self.from_len.setItemText(21, _translate("MainWindow", "хорватский"))
        self.from_len.setItemText(22, _translate("MainWindow", "чешский"))
        self.from_len.setItemText(23, _translate("MainWindow", "датский"))
        self.from_len.setItemText(24, _translate("MainWindow", "голландский"))
        self.from_len.setItemText(25, _translate("MainWindow", "эсперанто"))
        self.from_len.setItemText(26, _translate("MainWindow", "эстонский"))
        self.from_len.setItemText(27, _translate("MainWindow", "филиппинский"))
        self.from_len.setItemText(28, _translate("MainWindow", "финский"))
        self.from_len.setItemText(29, _translate("MainWindow", "французский"))
        self.from_len.setItemText(30, _translate("MainWindow", "фризский"))
        self.from_len.setItemText(31, _translate("MainWindow", "галисийский"))
        self.from_len.setItemText(32, _translate("MainWindow", "грузинский"))
        self.from_len.setItemText(33, _translate("MainWindow", "немецкий"))
        self.from_len.setItemText(34, _translate("MainWindow", "греческий"))
        self.from_len.setItemText(35, _translate("MainWindow", "гуджарати"))
        self.from_len.setItemText(36, _translate("MainWindow", "хауса"))
        self.from_len.setItemText(37, _translate("MainWindow", "гавайский"))
        self.from_len.setItemText(38, _translate("MainWindow", "иврит"))
        self.from_len.setItemText(39, _translate("MainWindow", "хинди"))
        self.from_len.setItemText(40, _translate("MainWindow", "хмонг"))
        self.from_len.setItemText(41, _translate("MainWindow", "венгерский"))
        self.from_len.setItemText(42, _translate("MainWindow", "исландский"))
        self.from_len.setItemText(43, _translate("MainWindow", "игбо"))
        self.from_len.setItemText(44, _translate("MainWindow", "индонезийский"))
        self.from_len.setItemText(45, _translate("MainWindow", "ирландский"))
        self.from_len.setItemText(46, _translate("MainWindow", "итальянский"))
        self.from_len.setItemText(47, _translate("MainWindow", "японский"))
        self.from_len.setItemText(48, _translate("MainWindow", "яванский"))
        self.from_len.setItemText(49, _translate("MainWindow", "каннада"))
        self.from_len.setItemText(50, _translate("MainWindow", "казахский"))
        self.from_len.setItemText(51, _translate("MainWindow", "кхмерский"))
        self.from_len.setItemText(52, _translate("MainWindow", "корейский"))
        self.from_len.setItemText(53, _translate("MainWindow", "курдский (курманджи)"))
        self.from_len.setItemText(54, _translate("MainWindow", "киргизский"))
        self.from_len.setItemText(55, _translate("MainWindow", "лаосский"))
        self.from_len.setItemText(56, _translate("MainWindow", "латинский"))
        self.from_len.setItemText(57, _translate("MainWindow", "латышский"))
        self.from_len.setItemText(58, _translate("MainWindow", "литовский"))
        self.from_len.setItemText(59, _translate("MainWindow", "македонский"))
        self.from_len.setItemText(60, _translate("MainWindow", "люксембургский"))
        self.from_len.setItemText(61, _translate("MainWindow", "малагасийский"))
        self.from_len.setItemText(62, _translate("MainWindow", "малайский"))
        self.from_len.setItemText(63, _translate("MainWindow", "малаялам"))
        self.from_len.setItemText(64, _translate("MainWindow", "мальтийский"))
        self.from_len.setItemText(65, _translate("MainWindow", "маори"))
        self.from_len.setItemText(66, _translate("MainWindow", "маратхи"))
        self.from_len.setItemText(67, _translate("MainWindow", "монгольский"))
        self.from_len.setItemText(68, _translate("MainWindow", "мьянма (бирманский)"))
        self.from_len.setItemText(69, _translate("MainWindow", "непальский"))
        self.from_len.setItemText(70, _translate("MainWindow", "норвежский"))
        self.from_len.setItemText(71, _translate("MainWindow", "пушту"))
        self.from_len.setItemText(72, _translate("MainWindow", "персидский"))
        self.from_len.setItemText(73, _translate("MainWindow", "польский"))
        self.from_len.setItemText(74, _translate("MainWindow", "португальский"))
        self.from_len.setItemText(75, _translate("MainWindow", "панджаби"))
        self.from_len.setItemText(76, _translate("MainWindow", "румынский"))
        self.from_len.setItemText(77, _translate("MainWindow", "самоанский"))
        self.from_len.setItemText(78, _translate("MainWindow", "шотландский гэльский"))
        self.from_len.setItemText(79, _translate("MainWindow", "сербский"))
        self.from_len.setItemText(80, _translate("MainWindow", "сесото"))
        self.from_len.setItemText(81, _translate("MainWindow", "шона"))
        self.from_len.setItemText(82, _translate("MainWindow", "синдхи"))
        self.from_len.setItemText(83, _translate("MainWindow", "сингальский"))
        self.from_len.setItemText(84, _translate("MainWindow", "словацкий"))
        self.from_len.setItemText(85, _translate("MainWindow", "словенский"))
        self.from_len.setItemText(86, _translate("MainWindow", "сомалийский"))
        self.from_len.setItemText(87, _translate("MainWindow", "испанский"))
        self.from_len.setItemText(88, _translate("MainWindow", "сунданский"))
        self.from_len.setItemText(89, _translate("MainWindow", "суахили"))
        self.from_len.setItemText(90, _translate("MainWindow", "шведский"))
        self.from_len.setItemText(91, _translate("MainWindow", "таджикский"))
        self.from_len.setItemText(92, _translate("MainWindow", "тамильский"))
        self.from_len.setItemText(93, _translate("MainWindow", "телугу"))
        self.from_len.setItemText(94, _translate("MainWindow", "тайский"))
        self.from_len.setItemText(95, _translate("MainWindow", "турецкий"))
        self.from_len.setItemText(96, _translate("MainWindow", "украинский"))
        self.from_len.setItemText(97, _translate("MainWindow", "урду"))
        self.from_len.setItemText(98, _translate("MainWindow", "узбекский"))
        self.from_len.setItemText(99, _translate("MainWindow", "вьетнамский"))
        self.from_len.setItemText(100, _translate("MainWindow", "валлийский"))
        self.from_len.setItemText(101, _translate("MainWindow", "коса"))
        self.from_len.setItemText(102, _translate("MainWindow", "идиш"))
        self.from_len.setItemText(103, _translate("MainWindow", "йоруба"))
        self.from_len.setItemText(104, _translate("MainWindow", "зулу"))
        self.from_text.setHtml(_translate("MainWindow",
                                          "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                                          "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n "
                                          "<html><head><meta name=\"qrichtext\" content=\"1\" /><style "
                                          "type=\"text/css\">\n "
                                          "p, li { white-space: pre-wrap; }\n"
                                          "</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; "
                                          "font-size:16pt; font-weight:400; font-style:normal;\">\n "
                                          "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; "
                                          "margin-left:0px; margin-right:0px; -qt-block-indent:0; "
                                          "text-indent:0px;\"><br /></p></body></html>"))
        self.to_lang.setItemText(0, _translate("MainWindow", "английский"))
        self.to_lang.setItemText(1, _translate("MainWindow", "русский"))
        self.to_lang.setItemText(2, _translate("MainWindow", "Африканский"))
        self.to_lang.setItemText(3, _translate("MainWindow", "гаитянский креольский"))
        self.to_lang.setItemText(4, _translate("MainWindow", "албанский"))
        self.to_lang.setItemText(5, _translate("MainWindow", "амхарский"))
        self.to_lang.setItemText(6, _translate("MainWindow", "арабский"))
        self.to_lang.setItemText(7, _translate("MainWindow", "армянский"))
        self.to_lang.setItemText(8, _translate("MainWindow", "азербайджанский"))
        self.to_lang.setItemText(9, _translate("MainWindow", "баскский"))
        self.to_lang.setItemText(10, _translate("MainWindow", "белорусский"))
        self.to_lang.setItemText(11, _translate("MainWindow", "бенгальский"))
        self.to_lang.setItemText(12, _translate("MainWindow", "боснийский"))
        self.to_lang.setItemText(13, _translate("MainWindow", "болгарский"))
        self.to_lang.setItemText(14, _translate("MainWindow", "каталонский"))
        self.to_lang.setItemText(15, _translate("MainWindow", "хауса"))
        self.to_lang.setItemText(16, _translate("MainWindow", "кебуано"))
        self.to_lang.setItemText(17, _translate("MainWindow", "чичева"))
        self.to_lang.setItemText(18, _translate("MainWindow", "китайский (упрощенный)"))
        self.to_lang.setItemText(19, _translate("MainWindow", "китайский (традиционный)"))
        self.to_lang.setItemText(20, _translate("MainWindow", "корсиканский"))
        self.to_lang.setItemText(21, _translate("MainWindow", "хорватский"))
        self.to_lang.setItemText(22, _translate("MainWindow", "чешский"))
        self.to_lang.setItemText(23, _translate("MainWindow", "датский"))
        self.to_lang.setItemText(24, _translate("MainWindow", "голландский"))
        self.to_lang.setItemText(25, _translate("MainWindow", "эсперанто"))
        self.to_lang.setItemText(26, _translate("MainWindow", "эстонский"))
        self.to_lang.setItemText(27, _translate("MainWindow", "филиппинский"))
        self.to_lang.setItemText(28, _translate("MainWindow", "финский"))
        self.to_lang.setItemText(29, _translate("MainWindow", "французский"))
        self.to_lang.setItemText(30, _translate("MainWindow", "фризский"))
        self.to_lang.setItemText(31, _translate("MainWindow", "галисийский"))
        self.to_lang.setItemText(32, _translate("MainWindow", "грузинский"))
        self.to_lang.setItemText(33, _translate("MainWindow", "немецкий"))
        self.to_lang.setItemText(34, _translate("MainWindow", "греческий"))
        self.to_lang.setItemText(35, _translate("MainWindow", "гуджарати"))
        self.to_lang.setItemText(36, _translate("MainWindow", "хауса"))
        self.to_lang.setItemText(37, _translate("MainWindow", "гавайский"))
        self.to_lang.setItemText(38, _translate("MainWindow", "иврит"))
        self.to_lang.setItemText(39, _translate("MainWindow", "хинди"))
        self.to_lang.setItemText(40, _translate("MainWindow", "хмонг"))
        self.to_lang.setItemText(41, _translate("MainWindow", "венгерский"))
        self.to_lang.setItemText(42, _translate("MainWindow", "исландский"))
        self.to_lang.setItemText(43, _translate("MainWindow", "игбо"))
        self.to_lang.setItemText(44, _translate("MainWindow", "индонезийский"))
        self.to_lang.setItemText(45, _translate("MainWindow", "ирландский"))
        self.to_lang.setItemText(46, _translate("MainWindow", "итальянский"))
        self.to_lang.setItemText(47, _translate("MainWindow", "японский"))
        self.to_lang.setItemText(48, _translate("MainWindow", "яванский"))
        self.to_lang.setItemText(49, _translate("MainWindow", "каннада"))
        self.to_lang.setItemText(50, _translate("MainWindow", "казахский"))
        self.to_lang.setItemText(51, _translate("MainWindow", "кхмерский"))
        self.to_lang.setItemText(52, _translate("MainWindow", "корейский"))
        self.to_lang.setItemText(53, _translate("MainWindow", "курдский (курманджи)"))
        self.to_lang.setItemText(54, _translate("MainWindow", "киргизский"))
        self.to_lang.setItemText(55, _translate("MainWindow", "лаосский"))
        self.to_lang.setItemText(56, _translate("MainWindow", "латинский"))
        self.to_lang.setItemText(57, _translate("MainWindow", "латышский"))
        self.to_lang.setItemText(58, _translate("MainWindow", "литовский"))
        self.to_lang.setItemText(59, _translate("MainWindow", "македонский"))
        self.to_lang.setItemText(60, _translate("MainWindow", "люксембургский"))
        self.to_lang.setItemText(61, _translate("MainWindow", "малагасийский"))
        self.to_lang.setItemText(62, _translate("MainWindow", "малайский"))
        self.to_lang.setItemText(63, _translate("MainWindow", "малаялам"))
        self.to_lang.setItemText(64, _translate("MainWindow", "мальтийский"))
        self.to_lang.setItemText(65, _translate("MainWindow", "маори"))
        self.to_lang.setItemText(66, _translate("MainWindow", "маратхи"))
        self.to_lang.setItemText(67, _translate("MainWindow", "монгольский"))
        self.to_lang.setItemText(68, _translate("MainWindow", "мьянма (бирманский)"))
        self.to_lang.setItemText(69, _translate("MainWindow", "непальский"))
        self.to_lang.setItemText(70, _translate("MainWindow", "норвежский"))
        self.to_lang.setItemText(71, _translate("MainWindow", "пушту"))
        self.to_lang.setItemText(72, _translate("MainWindow", "персидский"))
        self.to_lang.setItemText(73, _translate("MainWindow", "польский"))
        self.to_lang.setItemText(74, _translate("MainWindow", "португальский"))
        self.to_lang.setItemText(75, _translate("MainWindow", "панджаби"))
        self.to_lang.setItemText(76, _translate("MainWindow", "румынский"))
        self.to_lang.setItemText(77, _translate("MainWindow", "самоанский"))
        self.to_lang.setItemText(78, _translate("MainWindow", "шотландский гэльский"))
        self.to_lang.setItemText(79, _translate("MainWindow", "сербский"))
        self.to_lang.setItemText(80, _translate("MainWindow", "сесото"))
        self.to_lang.setItemText(81, _translate("MainWindow", "шона"))
        self.to_lang.setItemText(82, _translate("MainWindow", "синдхи"))
        self.to_lang.setItemText(83, _translate("MainWindow", "сингальский"))
        self.to_lang.setItemText(84, _translate("MainWindow", "словацкий"))
        self.to_lang.setItemText(85, _translate("MainWindow", "словенский"))
        self.to_lang.setItemText(86, _translate("MainWindow", "сомалийский"))
        self.to_lang.setItemText(87, _translate("MainWindow", "испанский"))
        self.to_lang.setItemText(88, _translate("MainWindow", "сунданский"))
        self.to_lang.setItemText(89, _translate("MainWindow", "суахили"))
        self.to_lang.setItemText(90, _translate("MainWindow", "шведский"))
        self.to_lang.setItemText(91, _translate("MainWindow", "таджикский"))
        self.to_lang.setItemText(92, _translate("MainWindow", "тамильский"))
        self.to_lang.setItemText(93, _translate("MainWindow", "телугу"))
        self.to_lang.setItemText(94, _translate("MainWindow", "тайский"))
        self.to_lang.setItemText(95, _translate("MainWindow", "турецкий"))
        self.to_lang.setItemText(96, _translate("MainWindow", "украинский"))
        self.to_lang.setItemText(97, _translate("MainWindow", "урду"))
        self.to_lang.setItemText(98, _translate("MainWindow", "узбекский"))
        self.to_lang.setItemText(99, _translate("MainWindow", "вьетнамский"))
        self.to_lang.setItemText(100, _translate("MainWindow", "валлийский"))
        self.to_lang.setItemText(101, _translate("MainWindow", "коса"))
        self.to_lang.setItemText(102, _translate("MainWindow", "идиш"))
        self.to_lang.setItemText(103, _translate("MainWindow", "йоруба"))
        self.to_lang.setItemText(104, _translate("MainWindow", "зулу"))
        self.label_6.setText(_translate("MainWindow", "↓"))
        self.reverse.setText(_translate("MainWindow", "↑↓"))
        self.to_text.setHtml(_translate("MainWindow",
                                        "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                                        "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n "
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style "
                                        "type=\"text/css\">\n "
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; "
                                        "font-size:16pt; font-weight:400; font-style:normal;\">\n "
                                        "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; "
                                        "margin-left:0px; margin-right:0px; -qt-block-indent:0; "
                                        "text-indent:0px;\"><br /></p></body></html>")) 
        self.translate_btn.setText(_translate("MainWindow", "Translate"))
        self.clear_btn.setText(_translate("MainWindow", "Сlear"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.action_2.setText(_translate("MainWindow", "Русский"))
        self.action_3.setText(_translate("MainWindow", "Англйский"))


class MyWidget(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super(MyWidget, self).__init__()
        self.setupUi(self)
        self.translate_btn.clicked.connect(self.trans)
        self.clear_btn.clicked.connect(self.clear)
        self.initUi()
        self.reverse.clicked.connect(self.res)

    def initUi(self):
        self.setWindowIcon(QIcon("Icons/trans.png"))

    def trans(self):
        """
            Метод перевода слов
        :return:
        """
        try:
            socket.gethostbyaddr('www.yandex.ru')
            # Получаем значения из comboBox
            combo_one = self.from_len.currentText()
            combo_two = self.to_lang.currentText()
            # Переводим эти значения на английский
            trans_one = Translator(from_lang="russian", to_lang="english")
            translation_one = trans_one.translate(combo_one)
            trans_two = Translator(from_lang="russian", to_lang="english")
            translation_two = trans_two.translate(combo_two)
            # Переводим основной контент
            translator = Translator(from_lang=translation_one, to_lang=translation_two)
            translation = translator.translate(self.from_text.toPlainText())

            self.to_text.setPlainText(translation)

        except socket.gaierror:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Проверьте соединение с интернетом")
            msg.setInformativeText('More information')
            msg.setWindowTitle("Error")
            msg.exec_()

    def res(self):
        from_len = self.from_len.currentText()
        to_len = self.to_lang.currentText()
        from_text = self.from_text.toPlainText()
        to_text = self.to_text.toPlainText()
        self.from_len.setCurrentText(to_len)
        self.to_lang.setCurrentText(from_len)
        self.from_text.setPlainText(to_text)
        self.to_text.setPlainText(from_text)


    def clear(self):
        """
            Очищаем поля ввода
        :return:
        """
        self.from_text.setPlainText('')
        self.to_text.setPlainText('')


if __name__ == "__main__":
    app = QApplication(sys.argv)
    ex = MyWidget()
    ex.show()
    sys.exit(app.exec_())
